language: rust
sudo: false
cache: cargo
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
script:
    - cargo build
    - cargo test
notifications:
    email: false
